# .github/workflows/build.yml
name: Build & Release App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Get App Info from package.json
        id: package
        uses: jaywcjlove/github-action-package@v4 # <-- THIS LINE IS THE FIX

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libasound2t64 libxtst-dev libxss1 libnss3 xvfb

      - name: Install dependencies
        run: npm install

      - name: Build Application Packages
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            xvfb-run --auto-servernum npx electron-forge make
          else
            npx electron-forge make
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Upload Artifacts to Private Repo Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TAG: ${{ github.ref_name }}
          APP_NAME: ${{ steps.package.outputs.name }}
        shell: bash
        run: |
          PRIVATE_REPO="iamplayerexe/${APP_NAME}_app"
          
          echo "Preparing to release version ${TAG} of ${APP_NAME} to ${PRIVATE_REPO}"

          # Create the release in the private repository, or ignore if it exists
          gh release create "${TAG}" --repo "${PRIVATE_REPO}" --title "${APP_NAME} ${TAG}" --notes "Automated release of ${APP_NAME} version ${TAG}." || echo "Release ${TAG} already exists. Proceeding to upload assets."

          # Upload all generated .zip and .dmg files from the 'out/make' directory
          echo "Uploading assets..."
          gh release upload "${TAG}" --repo "${PRIVATE_REPO}" --clobber out/make/**/*.{zip,dmg}

          echo "Release process complete."