name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    env:
      # The token MUST be passed for the publish command to work
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libasound2t64 libxtst-dev libxss1 libnss3 xvfb

      - name: Install dependencies
        run: npm install

      # --- CHANGE THE BUILD COMMAND TO 'publish' ---
      - name: Build and Publish
        # We can now use a single step because the logic is the same for all OS
        # The xvfb-run command for Linux is still needed
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            xvfb-run --auto-servernum npm run publish
          else
            npm run publish
          fi