name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*' # This workflow runs only when you push a new tag (e.g., v1.2.1)

jobs:
  build:
    strategy:
      fail-fast: false # Set to false so all jobs run even if one fails
      matrix:
        # Define the platforms to build on
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    # Use the virtual machine defined in the matrix
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a specific Node.js version

      # This step will only run on the ubuntu-latest job
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libasound2 libxtst-dev libxss1 libnss3 xvfb

      - name: Install dependencies
        run: npm install

      - name: Build the application
        # For Linux, we run the build command inside a virtual display server (xvfb)
        # This prevents errors related to the app not finding a screen.
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            xvfb-run --auto-servernum npm run make
          else
            npm run make
          fi
        env:
          # This token is required for publishing to GitHub Releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}